# fly.toml app configuration file generated for django-flyio-tailscale on 2026-04-29T15:02:55+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-flyio-tailscale'
primary_region = 'sin'

[[vm]]
  memory = '1gb'
  cpus = 1

# commented out to disable public access
#[http_service]
#  internal_port = 8000
#  force_https = true
#  auto_stop_machines = 'stop'
#  auto_start_machines = true
#  min_machines_running = 0

# this only works when serving publicly with fly proxy
#[[statics]]
#  guest_path = '/app/staticfiles'
#  url_prefix = '/static/'

[mounts]
  source = "data"
  destination = "/data"